<?php

use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->updateOrInsert(
            ['id' => 1],
            [
                'name' => 'English',
                'short_code' => 'eng',
                'lang_map' => '{
   "main":{
"create": "create",
"update": "update",
"created": "created",
"updated": "updated",
"delete": "delete",
"deleted": "deleted",
"add": "add",
"remove": "remove",
"added": "added",
"removed": "removed",
"select": "select",
"phone": "phone",
"phones": "phones",
"address": "address",
"address_line": "address line",
"list": "list",
"show": "show",
"edit": "edit",
"info": "info",
"additional": "additional",
"social": "social",
"new": "new",
"type": "type",
"city": "city   ",
"country": "country",
"email": "email",
"password": "password",
"name": "name",
"description": "description",
"actions": "actions",
"action": "action",
"item": "item",
"for": "for",
"at": "at",
"photo": "photo",
"post_code": "post_code",
"companies": "companies",
"company": "company",
"contacts": "contacts",
"contact": "contact",
"company_number": "company number",
"registration_date": "date of registration",
"website": "website",
"customers": "customers",
"customer": "customer",
"individuals": "individuals",
"individual": "individual",
"products": "products",
"product": "product",
"clients": "clients",
"client": "client",
"teams": "teams",
"team": "team",
"members": "members",
"member": "member",
"availability": "availability",
"tickets": "tickets",
"ticket": "ticket",
"status": "status",
"priority": "priority",
"from": "form",
"to": "to,",
"title": "title",
"last": "last",
"contact": "contact",
"due_date": "due_date",
"server": "server(for remote access)",
"access": "access",
"details": "details",
"attachments": "attachments",
"attachment": "attachment",
"answer": "answer",
"answers": "answers",
"history": "history",
"notices": "notices",
"notice": "notice",
"notes": "notes",
"note": "note",
"internal": "internal",
"roles": "roles",
"role": "role",
"person": "person",
"first_name": "firstname",
"last_name": "lastname",
"language": "language",
"postal_code": "postal code",
"title": "title",
"title_before_name": "title before name",
"loading": "Give me a second...",
"search": "Search...",
"items_per_page": "items per page",
"delete_selected": "do you want to delete selected",
"cancel": "cancel",
"basic": "basic",
"resend": "resend",
"invite": "invite",
"give_access": "give access to the system",
"information": "information",
"user": "user",
"save": "save",
"continue": "continue",
"supplier": "supplier"

   },
 "exceptions": {

 }
}'
            ]
        );
        DB::table('languages')->updateOrInsert(
            ['id' => 2],
            [
                'name' => 'Deutsch',
                'short_code' => 'deu',
                'lang_map' => '{
   "main":{
   "create": "erstellen",
"update": "aktualisierung",
"created": "erstellt",
"updated": "aktualisiert",
"delete": "löschen",
"deleted": "gelöscht",
"add": "hinzufügen",
"remove": "entfernen",
"added": "hinzugefügt",
"removed": "entfernt",
"select": "Wählen Sie",
"phone": "telefon",
"phones": "telefone",
"address": "adresse",
"address_line": "adresszeile",
"list": "liste",
"show": "anzeigen",
"edit": "bearbeiten",
"info": "infos",
"additional": "zusätzlich",
"social": "sozial",
"new": "neu",
"type": "geben Sie  ein",
"city": "stadt",
"country": "land",
"email": "E-Mail",
"password": "kennwort",
"name": "name",
"description": "beschreibung",
"actions": "aktionen",
"action": "aktion",
"item": "element",
"for": "für",
"at": "unter",
"photo": "foto",
"post_code": "postleitzahl",
"companies": "unternehmen",
"company": "unternehmen",
"contacts": "kontakte",
"contact": "kontakt",
"company_number": "firmennummer",
"registration_date": "datum der registrierung",
"website": "webseite",
"customers": "kunden",
"customer": "kunde",
"individuals": "personen",
"individual": "einzelperson",
"products": "produkte",
"product": "produkt",
"clients": "kunden",
"client": "kunde",
"teams": "team",
"team": "mannschaft",
"members": "mitglieder",
"member": "mitglied",
"availability": "verfügbarkeit",
"tickets": "eintrittskarten",
"ticket": "eintrittskarte",
"status": "status",
"priority": "priorität",
"from": "formular",
"to": "zu",
"title": "titel",
"last": "zuletzt",
"contact": "kontakt",
"due_date": "fälligkeitsdatum",
"server": "server (für fernzugriff)",
"access": "zugang",
"details": "einzelheiten",
"attachments": "anhänge",
"attachment": "anhang",
"answer": "antwort",
"answers": "antwortet",
"history": "geschichte",
"notices": "mitteilungen",
"notice": "hinweis",
"notes": "notizen",
"note": "notiz",
"internal": "intern",
"roles": "rollen",
"role": "rolle",
"person": "person",
"first_name": "vorname",
"last_name": "nachname",
"language": "sprache",
"postal_code": "postleitzahl",
"title": "titel",
"title_before_name": "titel vor Name",
"loading": "Gib mir eine Sekunde...",
"search": "Suche...",
"items_per_page": "objekte pro seite",
"delete_selected": "möchten Sie ausgewählte löschen",
"cancel": "stornieren",
"basic": "basic",
"resend": "erneut senden",
"invite": "einladen",
"give_access": "Geben Sie Zugriff auf das System",
"information": "information",
"user": "benutzer",
"save": "spare",
"continue": "fortsetzen",
"supplier": "lieferant"
 },
 "exceptions": {

 }
}'
            ]
        );
    }
}
