<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->updateOrInsert(
            ['id' => 1],
            [
                'name' => 'English',
                'short_code' => 'en',
                'locale' => 'en_US',
                'lang_map' => '{
  "sidebar": {
    "companies": "My Company",
    "customers": "Customer",
    "products": "Product",
    "teams": "Team",
    "individuals": "Individual",
    "individual": "Individual",
    "company": "Company",
    "customer": "Customer",
    "product": "Product",
    "team": "Team",
    "contact": "Contact",
    "ticket": "Ticket",
    "ticket_list": "Ticket list",
    "create_ticket": "Create ticket",
    "notify_customers": "Notify customers",
    "notification": "Notification",
    "knowledge_base": "Knowledge base",
    "settings": "Settings",
    "system_settings": "System settings",
    "general_settings": "General settings",
    "home": "Home",
    "profile": "Profile",
    "logout": "Logout",
    "all": "All"
  },
  "ticket_statuses": {
    "new": "New",
    "open": "Open",
    "responded": "Responded",
    "waiting_for_reply": "Waiting for reply",
    "closed": "Closed"
  },
  "ticket_priorities": {
    "urgent": "Urgent",
    "moderate": "Moderate",
    "low": "Low"
  },
  "ticket_categories": {
    "client": "Client",
    "notification": "Notification",
    "internal": "Internal"
  },
  "ticket_types": {
    "question" : "Question",
    "issue" : "Issue",
    "quote_request" : "Quote request",
  "internal": "Internal"
  },
  "history_actions": {
    "ticket_created": "Ticket created",
    "status_updated": "Status updated to ",
    "ticket_deleted": "Ticket deleted",
    "answer_added": "Responded",
    "notice_added": "Internal note added",
    "ticket_merged": "Ticket merged",
    "ticket_linked": "Ticket linked",
    "contact_attached": "Contact updated to ",
    "team_attached": "Team updated to ",
    "due_date_updated": "Due date updated to ",
    "employee_attached": "Assigned to ",
    "product_updated": "Product updated to",
    "access_details_updated": "Access details updated to ",
    "conn_details_updated": "Connection details updated to ",
    "category_updated": "Category updated to ",
    "company_updated": "Company updated to",
    "ticket_type_updated": "Type updated to "
  },
  "roles": {
    "superadmin": "Superadmin",
    "license_owner": "License owner",
    "company_admin": "Company admin",
    "company_manager": "Company manager",
    "regular_user": "Regular user",
    "company_client": "Company client",
    "contact": "Contact"
  },
  "company": {
    "company_number": "Company number",
    "registration_date": "Date of registration",
    "info": "Company info",
    "logo": "Logo",
    "additional_info": "Additional information",
    "company_contacts": "Company contacts",
    "resend_invite": "Resend invite",
    "edit_contact": "Edit contact",
    "delete_contact": "Delete contact",
    "new_contact": "New contact",
    "social_info": "Social media",
    "new_social_item": "New social media",
    "update_info": "Update info",
    "user_info": "User info",
    "user": "User",
    "product_categories": "Product categories",
    "new_product_category": "Add product category",
    "delete_product_category": "Delete product category",
    "parent_product_category": "Parent category",
    "product_category_created": "Product category created",
    "product_category_deleted": "Product category deleted",
    "update_phone": "Update phone",
    "phone_created": "Phone added",
    "phone_updated": "Phone updated",
    "phone_deleted": "Phone deleted",
    "update_address": "Update address",
    "address_created": "Address added",
    "address_updated": "Address updated",
    "address_deleted": "Address deleted",
    "update_social": "Update social link",
    "social_created": "Social link added",
    "social_updated": "Social link updated",
    "social_deleted": "Social link deleted",
    "update_email": "Update email",
    "email_created": "Email added",
    "email_updated": "Email updated",
    "email_deleted": "Email deleted",
    "new_notification_template": "Add new notification template",
    "notification_template_created": "Notification template created",
    "notification_template_deleted": "Notification template deleted",
    "notification_template_updated": "Notification template updated",
    "first_alias": "First line",
    "second_alias": "Second line",
    "employee_created": "Employee added",
    "employee_deleted": "Employee deleted",
    "employee_updated": "Employee updated",
    "employee_activated": "Employee activated",
    "employee_deactivated": "Employee deactivated",
    "customer_created": "Customer created",
    "customer_updated": "Customer updated",
    "customer_deleted": "Customer deleted",
    "user_created": "User created",
    "user_updated": "User updated",
    "user_deleted": "User deleted",
    "invitation_sent": "Invitation sent",
    "company_created": "Company created",
    "company_updated": "Company updated",
    "company_deleted": "Company deleted",
    "role_created": "Role created",
    "role_updated": "Role updated",
    "role_deleted": "Role deleted"
  },
  "customer": {
    "customer": "Customer",
    "add_new": "Add new customer",
    "supplier": "Supplier",
    "active": "Active",
    "product_info": "Product info",
    "show_product": "Show product",
    "delete_product": "Delete product",
    "product_deleted": "Product deleted"
  },
  "product": {
    "add_new": "Add new product",
    "info": "Product info",
    "product_clients": "Product clients"
  },
  "team": {
    "add_new": "Add new team",
    "info": "Team info",
    "members": "Agent",
    "new_member": "New team member"
  },
  "individuals": {
    "add_new": "Add new contact",
    "info": "User info",
    "active": "Active",
    "contact_info": "Contact info",
    "assigned_companies": "Linked companies",
    "new_customer": "Link to company",
    "update_link": "Update link",
    "is_active": "System access",
    "status": "Status",
    "social_info": "Social media"
  },
  "ticket": {
    "number": "Number",
    "contact_name": "Contact name",
    "contact_email": "Contact E-mail",
    "due_date": "Due date",
    "access_details": "Server access details",
    "status": "Status",
    "priority": "Priority",
    "company_from": "From company",
    "company_to": "To company",
    "company_contact": "Company contact",
    "product_name": "Product name",
    "title": "Title",
    "last_update": "Last update",
    "availability": "Availability",
    "ip_address": "IP address",
    "create_answer": "Reply",
    "create_ticket": "Create ticket",
    "add_attachments": "Add attachments",
    "ticket_answers": "Ticket answers",
    "ticket_actions": "Ticket actions",
    "assign_to": "Assign",
    "add_internal_note": "Add",
    "subject": "Subject",
    "internal_notes": "Internal notes",
    "ticket_history": "History",
    "access_data": "Access data",
    "merged_tickets": "Merged tickets",
    "availability_description": "Working hours",
    "ip_description": "IP addresses of your server for remote access if applicable",
    "access_description": "Please provide login details to your server for Teamviewer access, if applicable",
    "answer_description": "Write you answer here...",
    "no_assigned": "No agent assigned",
    "merge": "Merge",
    "is_spam": "Marked as Spam",
    "reported_by": "Reported by",
    "close_ticket":"Close ticket"
  },
  "main": {
    "create": "Create",
    "update": "Update",
    "created": "created",
    "updated": "updated",
    "delete": "delete",
    "deleted": "deleted",
    "add": "Add",
    "remove": "Remove",
    "added": "added",
    "removed": "removed",
    "select": "Select",
    "phone": "Phone",
    "phones": "Phones",
    "address": "Address",
    "address_line": "Address line",
    "list": "list",
    "show": "show",
    "edit": "edit",
    "info": "info",
    "additional": "additional",
    "social": "social",
    "new": "New",
    "type": "Type",
    "city": "City",
    "country": "Country",
    "street": "Street",
    "email": "Email",
    "password": "Password",
    "name": "Name",
    "name_de": "Name (in German)",
    "description": "Description",
    "new_phone": "New phone",
    "new_address": "New address",
    "new_email": "New email",
    "actions": "Actions",
    "action": "Action",
    "item": "Item",
    "for": "for",
    "at": "at",
    "photo": "Photo",
    "post_code": "Postcode",
    "category": "Category",
    "companies": "Companies",
    "company": "Company",
    "contacts": "Contacts",
    "contact": "Contact",
    "company_number": "Company number",
    "registration_date": "Date of registration",
    "website": "Website",
    "customers": "Customers",
    "customer": "Customer",
    "individuals": "Individuals",
    "individual": "Individual",
    "products": "Products",
    "product": "Product",
    "clients": "Clients",
    "client": "Client",
    "teams": "Teams",
    "team": "Team",
    "members": "Members",
    "member": "Member",
    "availability": "Availability",
    "tickets": "Tickets",
    "ticket": "Ticket",
    "status": "Status",
    "priority": "Priority",
    "from": "form",
    "to": "to,",
    "title": "Title",
    "last": "last",
    "due_date": "Due date",
    "server": "Server (for remote access)",
    "access": "Access",
    "details": "Details",
    "attachments": "Attachments",
    "attachment": "Attachment",
    "answer": "Answer",
    "answers": "Answers",
    "history": "History",
    "notices": "Notices",
    "notice": "Notice",
    "notes": "Notes",
    "note": "Note",
    "internal": "internal",
    "roles": "Roles",
    "role": "Role",
    "person": "person",
    "first_name": "Name",
    "last_name": "Surname",
    "language": "language",
    "postal_code": "Postcode",
    "title_before_name": "Title before name",
    "loading": "Give me a second...",
    "search": "Search...",
    "items_per_page": "Items per page",
    "delete_selected": "Do you want to delete selected",
    "cancel": "Cancel",
    "basic": "Basic",
    "resend": "Resend",
    "invite": "Invite",
    "give_access": "Give access to the system?",
    "information": "Information",
    "user": "User",
    "save": "Save",
    "save_as": "Save as...",
    "send": "Send",
    "continue": "Continue",
    "supplier": "Supplier",
    "responded": "responded",
    "close": "Close",
    "assign": "Assign",
    "timezone": "Timezone",
    "home": "Home",
    "profile_main": "Profile",
    "profile": "Profile",
    "subject": "Subject",
    "link": "Link",
    "none": "None",
    "generic_error": "Something went wrong",
    "icon": "Icon",
    "ticketing": "Ticketing",
    "do_not_show_this_again": "Do not show this again",
    "update_successful": "Update successful"
  },
  "system_settings": {
    "title": "System settings",
    "display": "Display",
    "navbar_style": "Navigation bar style",
    "navbar_no_logo": "Without company logo",
    "navbar_logo": "With company logo and company name, single line",
    "navbar_logo_2": "With company logo and company name, two lines",
    "navbar_only_logo": "Only company logo",
    "ticket_number_format": "Ticket number format",
    "ticket_number_format_help": "Ticket format can be composed from prefix (can be empty, up to 6 chars), delimiters (can be empty), date (in different formats) and daily sequence number",
    "ticket_number_format_prefix": "Prefix",
    "ticket_number_format_delimiter": "Delimiter",
    "ticket_number_format_date": "Date format",
    "ticket_number_format_sequence": "Daily sequence number length",
    "ticket_number_example": "Example: ",
    "default_timezone": "Default timezone",
    "languages": "Languages",
    "countries": "Countries",
    "company_theme_color": "Company theme color",
    "override_user_theme_color": "Override personal theme color",
    "override_user_theme_color_hint": "The change of the company theme color impacts all clients and all company users who did not select personal theme color",
    "phone_types": "Phone types",
    "new_phone_type": "Add new phone type",
    "phone_type_created": "Phone type created",
    "phone_type_deleted": "Phone type deleted",
    "phone_type_updated": "Phone type updated",
    "social_types": "Social media types",
    "new_social_type": "Add new social media type",
    "social_type_created": "Social media type created",
    "social_type_deleted": "Social media type deleted",
    "social_type_updated": "Social media type updated",
    "address_types": "Address types",
    "new_address_type": "Add new address type",
    "address_type_created": "Address type created",
    "address_type_deleted": "Address type deleted",
    "address_type_updated": "Address type updated",
    "email_types": "Email types",
    "new_email_type": "Add new email type",
    "email_type_created": "Email type created",
    "email_type_deleted": "Email type deleted",
    "email_type_updated": "Email type updated",
    "update_type_info": "Update information",
    "notification_types": "Notification types",
    "new_notification_type": "Add new notification type",
    "notification_type_created": "Notification type created",
    "notification_type_deleted": "Notification type deleted",
    "notification_type_updated": "Notification type updated"
  },
  "profile": {
    "user_theme_color": "Personal theme color",
    "show_speed_panel": "Show color floating gear",
    "revert_to_company_theme_color": "Change to default color",
    "login_email": "Login Email",
    "email_signatures": "Email signatures",
    "new_email_signature": "Add new Email signature",
    "signature": "Signature",
    "update_email_signature": "Update Email signature",
    "email_signature_created": "Email signature created",
    "email_signature_deleted": "Email signature deleted",
    "email_signature_updated": "Email signature updated"
  },
  "notification": {
    "template": "Template",
    "new_template": "New template",
    "select_template": "Select other template",
    "recipients": "Recipients",
    "new_email": "Add manually",
    "new_customer": "Add customer",
    "select_customer": "Select customer",
    "new_employee": "Add individual",
    "select_employee": "Select individual",
    "attributes": "Attributes",
    "due_date": "Due date",
    "priority": "Priority",
    "notification_type": "Notification type",
    "details": "Details",
    "subject": "Subject line",
    "text": "Text",
    "signature": "Signature",
    "priority_high": "High",
    "priority_medium": "Medium",
    "priority_low": "Low",
    "template_saved": "Template saved",
    "template_deleted": "Template deleted",
    "attachments": "Attachments",
    "new_attachment": "Add attachment",
    "select_file": "Select file",
    "delete_template": "Delete template?",
    "notification_sent": "Notification sent"
  },
  "exceptions": {

  }
}'
            ]
        );
        DB::table('languages')->updateOrInsert(
            ['id' => 2],
            [
                'name' => 'Deutsch',
                'short_code' => 'deu',
                'locale' => 'de_DE',
                'lang_map' => '{
  "sidebar": {
    "companies": "Meine Firma",
    "customers": "Firmen",
    "products": "Produkte",
    "teams": "Teams",
    "individuals": "Privatpersonen",
    "individual": "Privatpersonen",
    "contact": "Privatpersonen",
    "company": "Meine Firma",
    "customer": "Firmen",
    "product": "Produkt",
    "team": "Team",
    "ticket": "Ticket",
    "ticket_list": "Ticket Liste",
    "create_ticket": "Neues Ticket",
    "notify_customers": "Kontakte benachrichtigen",
    "notification": "Benachrichtigung",
    "knowledge_base": "Wissensdatenbank",
    "settings": "Die Einstellungen",
    "system_settings": "Systemeinstellungen",
    "general_settings": "Allgemeine Einstellungen",
    "home": "Home",
    "profile": "Profil",
    "logout": "Logout",
    "all": "Alle"
  },
  "ticket_statuses": {
    "new": "Neu",
    "open": "Offen",
    "responded": "Antwort pendent",
    "waiting_for_reply": "Warten auf Antwort",
    "closed": "Geschlossen"
  },
  "ticket_priorities": {
    "urgent": "Hoch",
    "moderate": "Normal",
    "low": "Niedrig"
  },
  "ticket_categories": {
    "client": "Kunde",
    "notification": "Benachrichtigung",
    "internal": "Intern"
  },
  "ticket_types": {
    "question" : "Frage",
    "issue" : "Problem",
    "quote_request" : "Angebotsanfrage",
    "internal": "Intern"
  },
  "history_actions": {
    "ticket_created": "Ticket erstellt",
    "status_updated": "Status aktualisiert auf ",
    "ticket_deleted": "Ticket gelöscht",
    "answer_added": "Antwortete",
    "notice_added": "Interne Notiz hinzugefügt",
    "ticket_merged": "Ticket verschmolzen",
    "ticket_linked": "Ticket verknüpft",
    "contact_attached": "Kontakt aktualisiert zu ",
    "team_attached": "Team aktualisiert zu ",
    "due_date_updated": "Fälligkeitsdatum aktualisiert auf ",
    "employee_attached": "Zugewiesen an ",
    "product_updated": "Produkt aktualisiert zu ",
    "access_details_updated": "Zugangsdetails aktualisiert auf ",
    "conn_details_updated": "Verbindungsdetails aktualisiert auf ",
    "category_updated": "Kategorie aktualisiert auf ",
    "company_updated": "Firma aktualisiert auf ",
    "ticket_type_updated": "Typ aktualisiert zu "
  },
  "roles": {
    "superadmin": "Höchster Vorgesetzter",
    "license_owner": "Lizenzinhaber",
    "company_admin": "Unternehmensadmin",
    "company_manager": "Firmenleiter",
    "regular_user": "Stammbenutzer",
    "company_client": "Firmenkunde",
    "contact": "Kontakt"
  },
  "company": {
    "company_number": "Firmennummer",
    "registration_date": "Datum der Registrierung",
    "info": "Firmeninfo",
    "logo": "Firmenlogo",
    "additional_info": "Zusätzliche Infos",
    "company_contacts": "Unternehmenskontakte",
    "resend_invite": "Einladen",
    "edit_contact": "Kontakt bearbeiten",
    "delete_contact": "Kontakt löschen",
    "new_contact": "Neuer Kontakt",
    "social_info": "Social Media",
    "new_social_item": "Neuer Eintrag",
    "update_info": "Updateinformation",
    "user_info": "Benutzerinformation",
    "user": "Benutzer",
    "update_phone": "Telefon aktualisieren",
    "phone_created": "Telefon hinzugefügt",
    "phone_updated": "Telefon aktualisiert",
    "phone_deleted": "Telefon gelöscht",
    "update_address": "Adresse aktualisieren",
    "address_created": "Adresse hinzugefügt",
    "address_updated": "Adresse aktualisiert",
    "address_deleted": "Adresse gelöscht",
    "update_social": "Social Link aktualisieren",
    "social_created": "Social Link hinzugefügt",
    "social_updated": "Social Link aktualisiert",
    "social_deleted": "Sozialer Link gelöscht",
    "update_email": "E-Mail aktualisieren",
    "email_created": "E-Mail hinzugefügt",
    "email_updated": "E-Mail aktualisiert",
    "email_deleted": "E-Mail gelöscht",
    "new_notification_template": "Neuen Mitteilungsvorlage hinzufügen",
    "notification_template_created": "Mitteilungsvorlage erstellt",
    "notification_template_deleted": "Mitteilungsvorlage gelöscht",
    "notification_template_updated": "Mitteilungsvorlage aktualisiert",
    "first_alias": "Erste Zeile",
    "second_alias": "Zweite Zeile",
    "employee_created": "Mitarbeiter hinzugefügt",
    "employee_deleted": "Mitarbeiter gelöscht",
    "employee_updated": "Mitarbeiter aktualisiert",
    "employee_activated": "Mitarbeiter aktiviert",
    "employee_deactivated": "Employee deaktiviert",
    "customer_created": "Kunde erstellt",
    "customer_updated": "Kunde aktualisiert",
    "customer_deleted": "Kunde gelöscht",
    "user_created": "Benutzer erstellt",
    "user_updated": "Benutzer aktualisiert",
    "user_deleted": "Benutzer gelöscht",
    "invitation_sent": "Einladung gesendet",
    "company_created": "Firma erstellt",
    "company_updated": "Firma aktualisiert",
    "company_deleted": "Firma gelöscht",
    "role_created": "Rolle erstellt",
    "role_updated": "Rolle aktualisiert",
    "role_deleted": "Rolle gelöscht"
  },
  "customer": {
    "customer": "Firma",
    "add_new": "Neuer Kunden hinzufügen",
    "supplier": "Lieferant",
    "active": "Aktiv",
    "show_product": "Produkt anzeigen",
    "delete_product": "Produkt löschen",
    "product_deleted": "Produkt gelöscht",
  },
  "product": {
    "add_new": "Neues Produkt hinzufügen",
    "info": "Produktinfo",
    "product_clients": "Produktkunden"
  },
  "team": {
    "add_new": "Neues Team hinzufügen",
    "info": "Teaminfo",
    "members": "Teammitglieder",
    "new_member": "Neues Teammitglied"
  },
  "individuals": {
  "add_new": "Neuen Kontakt hinzufügen",
  "info": "Allgemeines",
  "active": "Aktiv",
  "contact_info": "Zusätzliche Infos",
  "assigned_companies": "Kontakte",
  "new_customer": "Kontakt hinzufügen",
  "update_link": "Link aktualisieren",
  "is_active": "Systemzugriff",
  "status": "Status",
  "social_info": "Social Media"
  },
  "ticket": {
    "number": "Ticketnummer",
    "contact_name": "Kontaktname",
    "contact_email": "Kontakt E-mail",
    "due_date": "Deadline",
    "access_details": "Server Zugangsdaten",
    "status": "Status",
    "priority": "Priorität",
    "company_from": "Firma von",
    "company_to": "An die Firma",
    "company_contact": "Verantwortlich",
    "product_name": "Produktname",
    "title": "Titel",
    "last_update": "Letztes Update",
    "availability": "Verfügbarkeit",
    "ip_address": "IP Adresse",
    "create_answer": "Antwort erstellen",
    "create_ticket": "Ticket erstellen",
    "add_attachments": "Anhänge hinzufügen",
    "ticket_answers": "Ticket Antworten",
    "ticket_actions": "Ticketaktionen",
    "assign_to": "Zuweisen",
    "add_internal_note": "Interne Notiz hinzufügen",
    "internal_notes": "Interne Notizen",
    "ticket_history": "Ticketverlauf",
    "subject": "Betreff",
    "access_data": "Zugangsdaten",
    "merged_tickets": "Zusammengeführte Tickets",
    "availability_description": "Besprechungszeiten.",
    "ip_description": " IP-Adressen Ihres Servers für den Fernzugriff, falls vorhanden.",
    "access_description": "Bitte geben Sie uns Ihre Teamviewer Zugangsdaten zu Ihrem Server an, falls vorhanden.",
    "answer_description": "Schreiben Sie Ihre Antwort hier...",
    "no_assigned": "Kein Agent zugewiesen",
    "merge": "Zusammengeführen",
    "is_spam": "Marked as Spam",
    "reported_by": "Erstellt von",
    "close_ticket":"Ticket schliessen"
  },

   "main":{
   "create": "erstellen",
"update": "Update",
"created": "erstellt",
"updated": "aktualisiert",
"delete": "löschen",
"deleted": "gelöscht",
"add": "hinzufügen",
"remove": "entfernen",
"added": "hinzugefügt",
"removed": "entfernt",
"select": "Wählen Sie",
"phone": "Telefon",
"phones": "Telefone",
"address": "Adresse",
"address_line": "Adresszeile",
"list": "liste",
"show": "anzeigen",
"edit": "bearbeiten",
"info": "Infos",
"additional": "Zusätzlich",
"social": "sozial",
"new": "neu",
"type": "Wahlen sie",
"city": "Stadt",
"country": "Land",
"street": "Straße",
"email": "E-Mail",
"password": "Kennwort",
"name": "Name",
"name_de": "Name (Deutsch)",
"description": "Beschreibung",
"new_phone": "Telefon",
"new_address": "Adresse",
"new_email": "E-Mail",
"actions": "Aktionen",
"action": "Aktion",
"item": "element",
"for": "für",
"at": "unter",
"photo": "foto",
"post_code": "Postleitzahl",
"category": "Kategorie",
"companies": "unternehmen",
"company": "unternehmen",
"contacts": "kontakte",
"contact": "kontakt",
"company_number": "firmennummer",
"registration_date": "datum der registrierung",
"website": "webseite",
"customers": "Kunden",
"customer": "Kunde",
"individuals": "personen",
"individual": "einzelperson",
"products": "produkte",
"product": "produkt",
"clients": "Kunden",
"client": "Kunde",
"teams": "team",
"team": "mannschaft",
"members": "mitglieder",
"member": "mitglied",
"availability": "verfügbarkeit",
"tickets": "eintrittskarten",
"ticket": "eintrittskarte",
"status": "status",
"priority": "priorität",
"from": "formular",
"to": "zu",
"title": "titel",
"last": "zuletzt",
"due_date": "Deadline",
"server": "server (für fernzugriff)",
"access": "zugang",
"details": "einzelheiten",
"attachments": "Anhänge",
"attachment": "Anhang",
"answer": "antwort",
"answers": "antwortet",
"history": "geschichte",
"notices": "mitteilungen",
"notice": "hinweis",
"notes": "notizen",
"note": "notiz",
"internal": "intern",
"roles": "Rollen",
"role": "Rolle",
"person": "person",
"first_name": "Vorname",
"last_name": "Nachname",
"language": "Sprache",
"postal_code": "Postleitzahl",
"title_before_name": "Anrede",
"loading": "Gib mir eine Sekunde...",
"search": "Suche...",
"items_per_page": "Einträge pro Seite",
"delete_selected": "möchten Sie ausgewählte löschen",
"cancel": "stornieren",
"basic": "basic",
"resend": "erneut senden",
"invite": "einladen",
"give_access": "Berechtigung zum System erteilen?",
"information": "information",
"user": "benutzer",
"save": "spare",
"save_as": "Speichern als...",
"send": "Senden",
"continue": "fortsetzen",
"supplier": "lieferant",
"responded": "antwortete",
"close": "schließen",
"assign": "zuordnen",
"timezone": "Zeitzone",
"home": "home",
"profile_main": "profile",
"profile": "Profil",
"subject": "Gegenstand",
"link": "Verknüpfen",
"none": "Keiner",
"generic_error": "Etwas ist schief gelaufen",
"icon": "Symbol",
"ticketing": "Buchung",
"do_not_show_this_again": "Diese Mitteilung nicht mehr anzeigen",
"update_successful": "Aktualisierung erfolgreich"
 },
  "system_settings": {
    "title": "Systemeinstellungen",
    "display": "Anzeige",
    "navbar_style": "Design der Navigationsseitenleiste",
    "navbar_no_logo": "Ohne Firmenlogo",
    "navbar_logo": "Mit Firmenlogo und Firmenname, einzeilig",
    "navbar_logo_2": "Mit Firmenlogo und Firmenname, zwei Zeilen",
    "navbar_only_logo": "Nur Firmenlogo",
    "ticket_number_format": "Ticketnummer Format",
    "ticket_number_format_help": "Das Ticketformat kann aus Präfix (kann leer sein, bis zu 6 Zeichen), Trennzeichen (kann leer sein), Datum (in verschiedenen Formaten) und täglicher Sequenznummer bestehen",
    "ticket_number_format_delimiter": "Delimiter",
    "ticket_number_format_date": "Datumsformat",
    "ticket_number_format_sequence": "Tägliche Länge der Sequenznummer",
    "ticket_number_example": "Exempel: ",
    "default_timezone": "Standard Zeitzone",
    "languages": "Sprachen",
    "countries": "Länder",
    "company_theme_color": "Firmenmotivfarbe",
    "override_user_theme_color": "Überschreiben Sie die Farbe des persönlichen Themas",
    "override_user_theme_color_hint": "Die Änderung der Hintergrundfarbe hat Auswirkungen auf alle Kunden und Firmenbenutzer, die keine persönliche Hintergrundfarbe gewählt haben",
    "phone_types": "Telefontypen",
    "new_phone_type": "Neuen Telefontyp hinzfügen",
    "phone_type_created": "Telefontyp erstellt",
    "phone_type_deleted": "Phone type gelöscht",
    "phone_type_updated": "Telefontyp aktualisiert",
    "social_types": "Social Media",
    "new_social_type": "Neuen Sozialer Link hinzfügen",
    "social_type_created": "Sozialer Link erstellt",
    "social_type_deleted": "Sozialer Link gelöscht",
    "social_type_updated": "Sozialer Link aktualiziert",
    "address_types": "Adresstypen",
    "new_address_type": "Neuen Adresstyp hinzfügen",
    "address_type_created": "Adresstyp erstellt",
    "address_type_deleted": "Adresstyp gelöscht",
    "address_type_updated": "Adresstyp aktualisiert",
    "email_types": "E-Mail-Typen",
    "new_email_type": "Neuen E-Mail-Typ hinzufügen",
    "email_type_created": "E-Mail-Typ erstellt",
    "email_type_deleted": "E-Mail-Typ gelöscht",
    "email_type_updated": "E-Mail-Typ aktualisiert",
    "update_type_info": "Informationen aktualisieren",
    "notification_types": "Mitteilungstypen",
    "new_notification_type": "Neuen Mitteilungstyp hinzufügen",
    "notification_type_created": "Mitteilungstyp erstellt",
    "notification_type_deleted": "Mitteilungstyp gelöscht",
    "notification_type_updated": "Mitteilungstyp aktualisiert"
  },
  "profile": {
    "user_theme_color": "Persönliche Hintergrundfarbe",
    "show_speed_panel": "Colour floating bar anzeigen",
    "revert_to_company_theme_color": "Farbe des Firmenthemas benutzen",
    "login_email": "Einloggen E-Mail",
    "email_signatures": "E-Mail-Signaturen",
    "new_email_signature": "Neuen E-Mail-Signatur",
    "signature": "Signatur",
    "update_email_signature": "E-Mail-Signatur aktualisieren",
    "email_signature_created": "E-Mail-Signatur erstellt",
    "email_signature_deleted": "E-Mail-Signatur gelöscht",
    "email_signature_updated": "E-Mail-Signatur aktualisiert"
  },
  "notification": {
    "template": "Vorlage",
    "new_template": "Neue Vorlage",
    "select_template": "Andere Vorlage auswählen",
    "recipients": "Empfänger",
    "new_email": "Manuell hinzufügen",
    "new_customer": "Kunde hinzufügen",
    "select_customer": "Kunde auswählen",
    "new_employee": "Person hinzufügen",
    "select_employee": "Einzelperson auswählen",
    "attributes": "Attribute",
    "due_date": "Fälligkeitsdatum",
    "priority": "Priorität",
    "notification_type": "Mitteilungstyp",
    "details": "Details",
    "subject": "Betreffzeile",
    "text": "Text",
    "signature": "Unterschrift",
    "priority_high": "Hoch",
    "priority_medium": "Mittel",
    "priority_low": "Niedrig",
    "template_saved": "Vorlage aktualisiert",
    "template_deleted": "Vorlage gelöscht",
    "attachments": "Anhänge",
    "new_attachment": "Anhang hinzufügen",
    "select_file": "Datei aussuchen",
    "delete_template": "Vorlage löschen?",
    "notification_sent": "Mitteilung gesendet"
  },
  "exceptions": {

  }
}'
            ]
        );
    }
}
